from typing import Annotated

from fastapi import Depends

from fastapi import APIRouter

from app.services import (
    review_service,
)

from app.schemas.revenue import (
    MonthlyRevenue,
    RevenueVsOrders,
)
from app.schemas.order import MonthlyOrder
from app.schemas.category import CategoryRevenue
from app.schemas.payment import PaymentDistribution
from app.schemas.customer import CustomerByState
from app.schemas.review import ReviewDistribution


from app.utils.auth import get_authenticated_user
from app.services import category_service, customer_service, heatmap_service, order_service, payment_service, price_service, revenue_service

# All historical analytics require a logged-in user
router = APIRouter(
    prefix="/historical",
    tags=["Historical Analytics"],
    dependencies=[Depends(get_authenticated_user)],
)


# Return monthly revenue for the selected dataset
@router.get(
    "/monthly-revenue",
    response_model=list[MonthlyRevenue],
    summary="Monthly Revenue",
    description="Returns the total monthly revenue grouped by purchase month.",
    status_code=200,
    responses={
        200: {
            "description": "Monthly revenue retrieved successfully.",
            "content": {
                "application/json": {
                    "example": [
                        {"month": "2017-01", "revenue": 145230.75},
                        {"month": "2017-02", "revenue": 162985.40},
                    ]
                }
            },
        },
        500: {"description": "Internal Server Error"},
    },
)
async def monthly_revenue(
    dataset_id: str = "olist",
    current_user: dict = Depends(get_authenticated_user),
):
    return await revenue_service.monthly_revenue(
        dataset_id,
        current_user["id"],
    )


# Return monthly order counts for the selected dataset
@router.get(
    "/monthly-orders",
    response_model=list[MonthlyOrder],
    summary="Monthly Orders",
    description="Returns the total number of unique orders for each month.",
    status_code=200,
    responses={
        200: {
            "description": "Monthly orders retrieved successfully.",
            "content": {
                "application/json": {
                    "example": [
                        {"month": "2017-01", "orders": 748},
                        {"month": "2017-02", "orders": 912},
                    ]
                }
            },
        },
        500: {"description": "Internal Server Error"},
    },
)
async def get_monthly_orders(
    dataset_id: str = "olist",
    current_user: dict = Depends(get_authenticated_user),
):
    return await order_service.monthly_orders(
        dataset_id,
        current_user["id"],
    )


# Return revenue generated by each product category
@router.get(
    "/revenue-by-category",
    response_model=list[CategoryRevenue],
    summary="Revenue by Category",
    description="Returns revenue generated by each product category.",
    status_code=200,
    responses={
        200: {
            "description": "Category revenue retrieved successfully.",
            "content": {
                "application/json": {
                    "example": [
                        {"category": "Beauty & Health", "revenue": 285694.45},
                        {"category": "Sports & Leisure", "revenue": 254321.87},
                    ]
                }
            },
        }
    },
)
async def get_revenue_by_category(
    dataset_id: str = "olist",
    current_user: dict = Depends(get_authenticated_user),
):
    return await category_service.revenue_by_category(
        dataset_id,
        current_user["id"],
    )


# Return the categories performing best by revenue
@router.get(
    "/top-categories",
    response_model=list[CategoryRevenue],
    summary="Top Categories",
    description="Returns the highest revenue generating product categories.",
    responses={
        200: {"description": "Top categories retrieved successfully."},
        500: {"description": "Internal Server Error."},
    },
    status_code=200,
)
async def get_top_categories(
    dataset_id: str = "olist",
    current_user: dict = Depends(get_authenticated_user),
):
    return await category_service.top_categories(
        dataset_id=dataset_id,
        user_id=current_user["id"],
    )


@router.get(
    "/payment-distribution",
    response_model=list[PaymentDistribution],
    summary="Payment Distribution",
    description="Returns the distribution of payment methods used by customers.",
    status_code=200,
    responses={
        200: {
            "description": "Payment distribution retrieved successfully.",
            "content": {
                "application/json": {
                    "example": [
                        {"payment_type": "Credit Card", "count": 75863},
                        {"payment_type": "Bank Slip", "count": 19784},
                    ]
                }
            },
        }
    },
)
# Return the distribution of payment methods
async def get_payment_distribution(
    dataset_id: str = "olist",
    current_user: dict = Depends(get_authenticated_user),
):

    return await payment_service.payment_method_distribution(
        dataset_id,
        current_user["id"],
    )


# Return customer counts grouped by state
@router.get(
    "/customers-by-state",
    response_model=list[CustomerByState],
    summary="Customers by State",
    description="Returns the number of customers in each state.",
    responses={
        200: {"description": "Customer distribution by state retrieved successfully."},
        500: {"description": "Internal Server Error."},
    },
    status_code=200,
)
async def get_customers_by_state(
    dataset_id: str = "olist",
    current_user: dict = Depends(get_authenticated_user),
):
    return await customer_service.customers_by_state(
        dataset_id,
        current_user["id"],
    )


# Return the distribution of customer review scores
@router.get(
    "/review-distribution",
    response_model=list[ReviewDistribution],
    summary="Review Distribution",
    description="Returns the distribution of customer review scores.",
    responses={
        200: {"description": "Review score distribution retrieved successfully."},
        500: {"description": "Internal Server Error."},
    },
    status_code=200,
)
async def get_review_distribution(
    dataset_id: str = "olist",
    current_user: dict = Depends(get_authenticated_user),
):
    return await review_service.review_score_distribution(
        dataset_id,
        current_user["id"],
    )


# Return product prices grouped into ranges
@router.get(
    "/price-distribution",
    summary="Price Distribution",
    description="Returns the histogram of product prices divided into bins.",
    responses={
        200: {"description": "Price distribution retrieved successfully."},
        500: {"description": "Internal Server Error."},
    },
    status_code=200,
)
async def get_price_distribution(
    dataset_id: str = "olist",
    current_user: dict = Depends(get_authenticated_user),
):
    return await price_service.price_distribution(
        dataset_id=dataset_id,
        user_id=current_user["id"],
    )


# Return monthly revenue and orders for comparison
@router.get(
    "/revenue-vs-orders",
    response_model=list[RevenueVsOrders],
    summary="Revenue vs Orders",
    description="Returns monthly revenue alongside total orders for comparison.",
    responses={
        200: {"description": "Revenue vs Orders data retrieved successfully."},
        500: {"description": "Internal Server Error."},
    },
    status_code=200,
)
async def get_revenue_vs_orders(
    dataset_id: str = "olist",
    current_user: dict = Depends(get_authenticated_user),
):
    return await revenue_service.revenue_vs_orders(
        dataset_id,
        current_user["id"],
    )


@router.get(
    "/correlation-heatmap",
    summary="Correlation Heatmap",
    description="Returns correlation values between important business metrics for visualization as a heatmap.",
    responses={
        200: {"description": "Correlation matrix retrieved successfully."},
        500: {"description": "Internal Server Error."},
    },
    status_code=200,
)
async def get_correlation_heatmap(
    dataset_id: str = "olist",
    current_user: dict = Depends(get_authenticated_user),
):

    # Return the metric correlations used to build the heatmap
    return await heatmap_service.correlation_heatmap(
        dataset_id,
        current_user["id"],
    )

